name: Trigger auto deployment for reactapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/reactapp-AutoDeployTrigger-d1b97664-967c-41d4-b62b-1c3dd5e3e674.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.REACTAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: gitlima.azurecr.io
          registryUsername: ${{ secrets.REACTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REACTAPP_REGISTRY_PASSWORD }}
          containerAppName: reactapp
          resourceGroup: first
          imageToBuild: gitlima.azurecr.io/reactapp:${{ github.sha }}
          
            

     

